## => Site Settings
##############################
url: "https://neoreo.org"  # 사이트 도메인
baseurl: ""  # 루트 도메인 사용시 빈 값
title: neoreo  # 사이트 제목
description: > # 사이트 설명
  네오레오는 모바일 보드게임 전문 기업으로, 당신의 시간을 재미있게 만들어줍니다.

## => Language and Timezone
##############################
lang: "ko"  # 사이트 언어: 한국어로 설정
timezone: "Asia/Seoul"  # 대한민국 표준시 설정

## => Author and Social
##############################
author:
  type: "organization"  # 조직으로 설정
  name: Neoreo  # 조직 이름
  avatar: "/assets/images/logo.png"  # 로고 경로 (로고 이미지 추가 필요)
  bio: 네오레오는 모바일 보드게임 개발을 선도하는 기업입니다.
  email: nch6807@neoreo.com
  github: neoreo  # GitHub 링크

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: neoreo/repo_name  # GitHub 리포지토리 경로 입력
repository_tree: main  # 기본 브랜치 이름 설정

## => Paths
##############################
paths:
  root: "/"  # 루트 URL
  home: "/"  # 홈 URL
  archive: "/archive.html"  # 아카이브 페이지 URL
  rss: "/feed.xml"  # RSS 피드 URL

## => Sharing
##############################
sharing:
  provider: false  # 공유 버튼 비활성화

## => Comments
##############################
comments:
  provider: false  # 댓글 기능 비활성화

## => Analytics
##############################
analytics:
  provider: google  # Google Analytics 사용
  google:
    tracking_id: "UA-XXXXXXX-X"  # Google Analytics 추적 ID

## => Search
##############################
search:
  provider: default  # 기본 검색 엔진 사용

## => Build
##############################
markdown: kramdown  # 마크다운 엔진 설정
highlighter: rouge  # 코드 하이라이터
permalink: pretty  # URL을 사람이 읽기 좋은 형식으로 설정

exclude:
  - README.md
  - CHANGELOG.md
  - /node_modules
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      pageview: true
      aside:
        toc: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
